### ISSUE TITLE
Mockup View 2 ( Login )

### ISSUE THREAD

**Issue by ymdx** [OSWeekends/SentryJS#13]
![login](https://cloud.githubusercontent.com/assets/24206092/23729040/17b8d77e-0460-11e7-970f-bed73dc396d7.png)

**Comment by carquet** [comment]
both login and signup pages are clear and to the point.
We are going to have to think about a REAL name for that app. Sentry already exists!

**Comment by Monzonprog** [comment]
I like the design, it´s very clear. I think the same, we need a new name.
